### ISSUE TITLE
Paginar claves de espinoso

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#1]
Ej:

**Un cactus**
> espinoso, claves?

**Espinoso**
> Reconozco estas: 
> /macri.?$/i
> /espinoso.?$/i
> /marcos.?$/i
> /maximo.?$/i
> /facu.?$/i
> /dan.?$/i
> _Si querés ver las siguientes escribí_ `espinoso claves page 2`
> _Si querés ver todas de una entrá al repo, pajero!_

**Comment by danwyryunq** [comment]
porque??? para que? Realmente no lo veo necesario.
Sí  creo que podríamos hacer algo más agradable las claves, quizás reemplazar algunas cosas del regex para que sean más legibles a la vista, y no hayan confusiones con cosas como los signos de pregunta que significa opcionalidad, mientras que al que no está familiarizado le suena a que tiene que haber un signo de pregunta escrito.

**Comment by leandrojdl** [comment]
Porque es una paja que tire un listado tan largo de comandos/mensajes. Y pensá que vamos a agregarle muchos más.

Qué pasa si espinoso reconoce 50 mensajes? Vas a tener 50 líneas cuando le pidas los mensajes que entiende? A mi no me gustaría.

**Comment by danwyryunq** [comment]
no hay chance de que se los mande por un mensaje privado al solicitante ?

**Comment by leandrojdl** [comment]
no sé, tendremos que investigar... también uno se puede poner a chatear con el bot de forma privada sin necesidad del grupo...

lo que yo digo es que es paja que tire bocha de lineas de mensajes pq molesta y mucho... es cuestión de ver cuál es la mejor solución.

Yo voy tirando issues y vamos viendo qué se puede o si deriva en algo superador

**Comment by leandrojdl** [comment]
Esto quedó viejo
