### ISSUE TITLE
Ver el calculo de la cantidad de días de los feriados

### ISSUE THREAD

**Issue by marivgil** [12-cactus/espinoso#102]
Probablemente se arregle con el cambio de año, desconozco. Al día de hoy (26-12-2017) esta retornando esto:

Manga de vagos, quedan 16 feriados en todo el año.
 - Domingo 01 de Enero, Año Nuevo (359 días)
 - Lunes 27 de Febrero, Carnaval (302 días)
 - Martes 28 de Febrero, Carnaval (301 días)
 - Viernes 24 de Marzo, Día Nacional de la Memoria por la Verdad y la Justicia (277 días)
 - Domingo 02 de Abril, Día del Veterano y de los Caídos en la Guerra de Malvinas (268 días)
 - Viernes 14 de Abril, Viernes Santo (256 días)
 - Lunes 01 de Mayo, Día del Trabajador (239 días)
 - Jueves 25 de Mayo, Día de la Revolución de Mayo (215 días)
 - Sabado 17 de Junio, Día Paso a la Inmortalidad del General Don Martín de Güemes (192 días)
 - Martes 20 de Junio, Día Paso a la Inmortalidad del General Manuel Belgrano (189 días)
 - Domingo 09 de Julio, Día de la Independencia (170 días)
 - Lunes 21 de Agosto, Paso a la Inmortalidad del General José de San Martín (127 días)
 - Lunes 16 de Octubre, Día del Respeto a la Diversidad Cultural (71 días)
 - Lunes 20 de Noviembre, Día de la Soberanía Nacional (36 días)
 - Viernes 08 de Diciembre, Inmaculada Concepción de María (18 días)
 - Lunes 25 de Diciembre, Navidad (1 días)

**Comment by leandrojdl** [comment]
Es el feriados se siempre, esa cosa fea de Dan o ya está contra la API?

**Comment by marivgil** [comment]
Es esa cosa fea de Dan.
Hace mucho que vi eso y mi memoria es frágil, peeeero si no recuerdo mal, si usamos la api se pierde la cuenta de días. Quiero decir que de todas maneras habría que calcularla por fuera

**Comment by leandrojdl** [comment]
Con `Carbon` es una gilada el parseo y el cálculo de días. Cuando le peguemos a la API restructuramos toda esta chota
