### ISSUE TITLE
agregar validación cuando se consulta por tags q no existen

### ISSUE THREAD

**Issue by Espinoso12** [12-cactus/espinoso#121]

**Comment by leandrojdl** [comment]
cuando pedís `ver #tag` de uno que no existe pasan dos cosas que deberían arreglarse:

- al chat no le dice nada, **debería darle un mensaje de error o que no hay nada**
- tira una exception `Fuck! Something blow up on App\Handlers\TagsHandler
- Error Message: Trying to get property of non-object`

**Comment by marivgil** [comment]
hecho
