### ISSUE TITLE
Agenda de Cumpleaños

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#124]
Generar una funcionalidad de Agenda de Cumpleaños para un chat específico.

### Etapa 1

Generar un handler multicomando (ver TagsHandler para referencias) en donde se puedan recibidor estos comandos:

> espi cumple @username
> @username cumple el 22/11

> espi cumple @username 11/11
> Listo vieja!

**Es importante que @username sea el usuario etiquetado.**

Si no tiene definido username igual tiene que ser el usuario etiquetado. Hay que revisar como recibe Telegram las etiquetas.

En esta etapa solo importa que reciba los mensajes y responda cualquier cosa hardcodeada, no hace falta persistir aún.

### Etapa 2

Persistir! Usar Migrations y Eloquent

La idea puede ser tener una tabla `birthdays` con los campos: `<id PK AUTO, telegram_chat_id FK, telegram_user_id FK, date>`

Cuando llega un mensaje de consulta, se retorna el dato, cuando se esta seteando, se guarda.

### Etapa 3

Generar una tarea programada usando el scheduling de laravel
https://laravel.com/docs/5.5/scheduling

Se puede definir un cron que todos los días a las 10 de la mañana revise la tabla de cumpleaños y mande un mensaje a ese chat con un mensaje de cumpleaños para esa persona.

--

Te animás @sirDemian? Cómo lo ves @marivgil?

**Comment by marivgil** [comment]
¿No se podrá reutilizar algo del SettingsHandler para la 1er etapa?

Me da mucha curiosidad el scheduling de laravel que mencionas :) ... lo voy a investigar si estoy al pedo en el laburo (pinta que si ¬¬)
