### ISSUE TITLE
actualizar el README con la info de correr las migrations

### ISSUE THREAD

**Issue by Espinoso12** [12-cactus/espinoso#125]
no solo hay que verificar el orden de la key del clima sino que hay que agregar que es necesario correr el comando de migrations

**Comment by leandrojdl** [comment]
es realmente necesario esto? yo hice la instalación con un nuevo homestead y no tuve que tirar las migrations... creo que con composer install o alguna de esas se corre... habría que verificarlo...

**Comment by marivgil** [comment]
Desconozco... yo no tuve que hacer nada de eso, con el readme como estaba salí andando. Sir tuvo algunos problemas, de ahí nació este issue.
Lo cierro y si en algún momento alguien tiene que hacerlo para levantar el ambiente, lo volvemos a charlar.
