### ISSUE TITLE
estaría muy bueno tener un log de la última excepción lanzada y cuando le preguntas "que pasó Espí" te la mande

### ISSUE THREAD

**Issue by Espinoso12** [12-cactus/espinoso#127]

**Comment by leandrojdl** [comment]
@marivgil me parece insteresante, pero dame más detalle de lo que pensás a ver qué se me ocurre.

Hoy hace esto mandando la exception al chat de debug, pero no sé si lo que vos planteas difiere mucho de eso o no.

**Comment by marivgil** [comment]
Se le ocurrió a Dan y pasado medio año no creo que tenga ni idea de lo que había pensado...
Ir guardando los errores en la base para después consultarlos, si bien se usa en muchas aplicaciones, lo que me frenó a arrancarlo es que en algún momento vamos a tener que ir depurando esa tabla y.... ¿Quien se va a acordar de hacerlo?
Voto por el "Ya fue"

**Comment by leandrojdl** [comment]
ya fue...
