### ISSUE TITLE
[Tags] Poder administrar los tags del grupo desde el chat personal

### ISSUE THREAD

**Issue by Espinoso12** [12-cactus/espinoso#133]

**Comment by marivgil** [comment]
Me cuesta estar de acuerdo con esto... habías trabajado en identificar los chats justamente para que no se comparta información entre ellos... creo que esto va en contra de esa idea inicial.
Además, no le encuentro mucha utilidad salvo el anonimato de acciones que en verdad le incumben a un grupo

**Comment by leandrojdl** [comment]
La idea no es compartir info, sino poder administrar y que no aparezcan mil mensajitos en el grupo. Como ayer que me puse a revisar y limpiar tags y todo eso fue como 10 mensajes. Quizas eso poder hacerlo desde afuera, pero seguirían siendo los del chat.

Igual es cierto, estarías tomando acciones "ocultas". Hasta que alguien no revise puntualmente no va a saber que pasó. Es cierto, no sé si si está bueno, además es complejo creo. Vuela.
