### ISSUE TITLE
fijarse si se pueden agregar los feriados puentes a la funcionalidad de feriados

### ISSUE THREAD

**Issue by Espinoso12** [12-cactus/espinoso#149]
1. revisar en la api si aparecen los feriados puentes
2. si no aparecen, bueno... a comerla
3. si aparecen hay que ver bajo que type y permitir que se agreguen esos tambien
4. facu puto

**Comment by leandrojdl** [comment]
ya se ven los puentes, solo que el puente del 30/4 no está cargado..

cierro el issue
