### ISSUE TITLE
to-talk list

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#29]
In a group, it would be nice to keep a list of topic that the group need to talk or something.

Example:

**jon**
espi lista de temas

**espinoso**
Se pide por favor, no? Igual te los paso
 - teoría de la relatividad
 - física cuántica
 - inteligencia artificial
 - dan y su tip
 - facu puto

**Comment by marivgil** [comment]
Ya que estas mirando.... ¿Este no sería igual a #39?
Tampoco recuerdo que fue lo que se habló

**Comment by leandrojdl** [comment]
puede que si, puede que no... realmente no recuerdo...

El #39 pareciera ser una generalizacion de este...

No sé... qué opinás?

**Comment by marivgil** [comment]
Se continua este tema en #39
