### ISSUE TITLE
el handler de cine no debería traer próximos estrenos

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#30]

**Comment by marivgil** [comment]
mmm ¿Seguro que trae próximo estrenos? mepa que no. De todas maneras la url que estamos consultando no tiene fecha de estreno como para filtrar...

http://www.hoyts.com.ar/ajaxCartelera.aspx?filter=Home&cine=&premium=False&_=1493929858090

Lo que si creo que tal vez estaría bueno es agregar el href que te lleva a la pagina que tiene una breve reseña de la peli... me parece útil

**Comment by leandrojdl** [comment]
parece que lo dije yo pero no, lo dijo dan... en esa época los issues estaban asociados a mi user

la verdad que ni idea, nunca le di mucha bola al coso del cine

**Comment by leandrojdl** [comment]
cierro porque no parece pasar esto
