### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#39]

**Comment by marivgil** [comment]
Se quiere mapear un tag con una lista de mensajes.

**#tag** <cosa a guardar>
Guardo el mnj

**espi tags**
Respondo con lo que tengo guardado:
_Tengo estas mierdas:
- <cosa a guardar>
- ...
- ..._

**#tag clear**
elimino lo guardado al momento.

**Comment by leandrojdl** [comment]
Vuelvo con esta idea, paso en limpio:

**Caso 1: Guardar algo en un _tag_**

`[espi] #tagName <text>`

**Maru** #list dark
**Espi** Guardado! Para ver lo que hay en #list escribí `[espi] show #list`

**Maru** #stickers alguno para JP
**Espi** Guardado! Para ver lo que hay en #stickers escribí `[espi] show #stickers`

**Caso 2: Ver todo lo que hay en un _tag_**

`[espi] show|ver|list|listar #tagName`

**Maru** show #list
**Espi** Esto es lo que hay en #list:
  - dark

**Caso 3: Ver todos los tags que info**

`[espi] tags`

**Maru** tags
**Espi** Tags con data:
  - #list
  - #stickers

**Caso 4: Limpiar un tag**

`[espi] clean|clear|limpiar|vaciar #tagName`

**Maru** clean #stickers
**Espi** Listo vieja!
