### ISSUE TITLE
Estándarizar mensajes

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#4]
Que los que son pedidos de data tengan que comenzar con `espinoso`. Ej:

> espinoso, ayuda gsm
> espinoso ig candetinelli

Pero que otros sean más naturales, Ej:

> **Maru**
> dan, como anda ese tip?
> **Espinoso**
> dale dan, dejá de pajearte conmigo y terminá el tip

**Comment by danwyryunq** [comment]
no me gusta, creo que agregar mas palabras para comandos es molesto para los celulares... 
Particularmente, para los comandos prefiero lo que elegí yo, keywords bien cortas, y que el mensaje  comience con la keyword y termine donde terminan los parámetros, de manera que una porción de un mensaje no puede ser interpretado como comando.
es decir, que matchee
/^KEYWORD PARAMS$/

Ej: 
`ig 9gag`  << esto si se toma como comando
`marcos dijo que ig 9gag debería ser un alias` << esto no

**Comment by leandrojdl** [comment]
si, mientras los mensajes no comiencen con algo que pueda no tener la intención...

además fijate que, sin querer, dijiste comando... lo cual tiene sentido...

la otra opción es pasar esos mensajes a comandos, de manera de quedar:

```
/ig 9gag
```

**Comment by danwyryunq** [comment]
no fue sin querer, pero si, me gust gusta, aunque quiero lograr que los comandos sean rápidos desde el celular. empezar con barra ya implica cambiar el tecladito al modo de símbolos solo para empezar, estaría bueno empezarlos ponele con punto o algún caracter que esté en el teclado alfabético.
Mañana voy a leer un poco la documentación a ver como funciona realmente la sdk, ya me están dando un poco de paja los regexes para parsear todos los comandos

**Comment by mdAlvarenga** [comment]
Adhiero completamente al hecho de que sea bien cómodo para el teclado alfanumérico. Pero por otro lado, que tengas decir: Espinoso ..... , no me parece que esté mal, ni que agregue DEMASIADO a los comandos. E incluso, me parece más natural con el rol que espinoso tiene o le queremos dar en el grupo, de ser "uno más".

**Comment by leandrojdl** [comment]
Done!
