### ISSUE TITLE
https://github.com/spatie/laravel-collection-macros/

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#48]

**Comment by leandrojdl** [comment]
no tiene mucho sentido un issue que sea agregar un packages... además, si bien las macros parecen copadas, me suena a que vas a estar buscando metodos en la doc de laravel y te vas a volver loco pq te olvidaste que esto existe...

**Comment by marivgil** [comment]
Este igual lo voy a meter

**Comment by leandrojdl** [comment]
ahora voy a agregar esto, te dejo el link de como se pueden hacer más macros en caso de que necesitemos

yo pensaba que íbamos a tener que usar el package de ellos, pero no, lo que hacen es extender Collection mediante macros... muy groso

**Comment by leandrojdl** [comment]
lo había agregado en el commit d64ad11a
