### ISSUE TITLE
fix message that something has blowed up, doest show user name

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#50]

**Comment by marivgil** [comment]
¿Este no esta cocinado ya???
En EspinosoHandler.php->handleError

**Comment by leandrojdl** [comment]
En realidad no, pq cuando el user no tiene username en vez de mostrar el nombre no muestra nada.

Igual, #55 contradice esto, pq la idea es sacar datos sensibles del BlowUp. No tiene sentido ver quien escribió el mensaje, solo importa el mensaje en sí.

Así que lo cierro :)
