### ISSUE TITLE
definir fechas de asado por chat

### ISSUE THREAD

**Issue by Espinoso12** [12-cactus/espinoso#53]

**Comment by leandrojdl** [comment]
cómo sería este feature?

**Comment by marivgil** [comment]
La verdad no tengo idea, es viejo y no recuerdo que se habló. Pero me sirvió de excusa para empezar a ver lo de la base...
Me imagine recibir un mensaje con la próxima fecha y que espi lo guarde.... fin?

**Comment by leandrojdl** [comment]
Aprovecho para comentarte algo... el otro día arreglando lo del webhook de github instalé una librería que permite manejar de forma cómoda el seteo de cosas del estilo key-value en la base.

Se podría usar para setear el asadoodle. La sintaxis es asi:

```
$value = Setting::get('asadoodle');
Setting::set('asadoodle', $newValue);
```

Lo que sí habría que generar las key en espi, algo asi:

`espi asadoodle` tira el link

`espi set asadoodle http://tu-hermana.gob.ar`

**Comment by leandrojdl** [comment]
creo que este issue ya no tiene sentido @marivgil 

se puede usar el `set` para guardar datos

lo cierro, si te parece que da para alguna cosa más, reabrilo
