### ISSUE TITLE
Storing Users data in BD

### ISSUE THREAD

**Issue by danwyryunq** [12-cactus/espinoso#6]
Configurar la BD en heroku (Necesitasmamos el usuario de Alan para esto creo)  e integrarla en el proyecto.

**Comment by leandrojdl** [comment]
When Espi receives an `$update` it should will store user info in a table.

- telegram_id
- first_name
- last_name
- username

Check user data in every interaction is not a good idea. It's just to create interaction with model.

To do next: Check which interactions are captured (start chat, change name, change group name, add member to group, etc...)
