### ISSUE TITLE
buscar gente de fb (y/u otras redes sociales)

### ISSUE THREAD

**Issue by danwyryunq** [12-cactus/espinoso#7]
Se me ocurre un comando fbs (fb search, como para que no descartar la posibilidad futura de un comando fb que directamente traiga datos del usuario específico de fb) 
que se use de esta manera
`fbs mariano perez`
y devuelva un mensaje con los primeros , digamos 10 resultados de la búsqueda. 

Un problema es que un mensaje con los nombres solos no ayudaría mucho, necesitaríamos imágenes y hasta donde ví solo se puede mandar una foto por mensaje, lo cual sería muy molesto si queremos n>1 resultados. ¿Habrán herramientas para generar una imagen con todas las fotitos y nombres en una sola, y meterlas en un cdn, sin hacernos transferir datos al server?

*Filtros*
Se podrían agregar filtros, después del nombre, separándolos por comas teniendo en cuenta que siempre lo que viene antes de la primera coma es el nombre, y lo demás puede ser cualquier otro dato de lo que traiga el grafo de fb.
`fbs mariano perez, unq, swing, blah`

https://developers.facebook.com/docs/graph-api/using-graph-api/

**Comment by leandrojdl** [comment]
salvo que alguien esté interesado en hacer esta integracion, cierro esto
