### ISSUE TITLE
Mejorar el regex del saludo de espinoso

### ISSUE THREAD

**Issue by leandrojdl** [12-cactus/espinoso#8]
Actualmente espinoso response al `espinoso, como andas?`

Debería responser (al menos) a las siguientes frases:

* `espinoso como andas?`
* `espinoso como estas?`
* `como andas espinoso?`
* `como estas espinoso?`

**Comment by marivgil** [comment]
Ya responde a 
espinoso como andas?
espinoso como estas?

agregar 

como andas espinoso?
como estas espinoso?
