### ISSUE TITLE
transcripicón de audios usando alguno de estos motores: wit.ai o Yandex SpeechKit

### ISSUE THREAD

**Issue by Espinoso12** [12-cactus/espinoso#86]

**Comment by marivgil** [comment]
https://github.com/ZloeSabo/speechkit-php

https://tech.yandex.com/speechkit/cloud/doc/guide/concepts/about-docpage/

**Comment by leandrojdl** [comment]
Para la transcripción por ahora voy a usar SpeechKit por ser más simple y específico.

Pero hay que darle una mirada a wit.ai porque es un golazo para parsear expresiones y que espi pueda recibir comandos por voz
