### ISSUE TITLE
Agregar Issues a travez de un command en telegram

### ISSUE THREAD

**Issue by mdAlvarenga** [12-cactus/espinoso#9]
La idea es la que propuso Agus, y lo escribo yo porque se olvidó! 
Poder hacer la integración con GIT, que mediante algún comando aún por definir, se puedan cargar issues directamente desde el chat de telegram!
Esto parece el issue de entre los issues! jajaaj

**Comment by leandrojdl** [comment]
Inception done!
Command: `espi issue title text`
